name: Check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false
      - run: node --check main.js
      - run: node --check preload.js
      - run: npm test
